// ===========================================================================
// type-program-source.ts — the program the compiler is actually handed.
//
// Every clause of the flagship claim is in here and none of it is stubbed:
// a root type, `FormAdapter<Root, FieldPath<Root>>`, the module augmentation
// that registers it, and real `useField` calls. The imports resolve to the
// packages' SOURCE, so what is measured is the type the repository maintains
// rather than a `.d.ts` that may have been emitted before the last edit.
//
// `declare const adapter` rather than a resolver call, because a resolver
// would drag zod's own inference into the number and the question here is what
// the ADDRESSING costs. The registration is otherwise the one a reader of
// `form-type-registry.ts` is shown, character for character.
//
// The baseline is this same file with an empty function body. That matters
// more than it looks: `FieldPath<Root>` sits in a type annotation, so the
// compiler resolves it whether or not anybody calls `useField`. Subtracting
// the baseline therefore leaves the cost of ADDRESSING alone, with the union's
// construction already paid — which is the decomposition the report needs and
// the one the disagreeing probes did not make.
// ===========================================================================
import type { ShapeUnderTest } from "./shape-under-test.types.ts";

const BANNER = `// Generated by \`npm run bench:types\`. Rewritten on every program and
// deleted when the run ends. Nothing here is meant to be read by a person.`;

/** A program with no form-contract in it at all — the lib.d.ts floor. */
export const EMPTY_PROGRAM_SOURCE = `${BANNER}\nexport {};\n`;

/**
 * The packages, imported and never used for anything. It separates what the
 * libraries' own source costs from what one application's shape costs, so the
 * shape rows are not reported as if they contained the `./react` entry's own
 * type-checking.
 */
export const PACKAGES_ONLY_PROGRAM_SOURCE = `${BANNER}
import type { FieldPath, FormAdapter } from "@maroonedog/form-contract";
import { useField } from "@maroonedog/form-contract/react";

export type Unused = [FieldPath<{ only: string }>, FormAdapter<unknown>];
export const alsoUnused = useField;
`;

/** The flagship shape, with one `useField` call per path given. */
export function typeProgramSource(
  shape: ShapeUnderTest,
  calledPaths: readonly string[]
): string {
  const calls = calledPaths
    .map((path) => `  useField(${JSON.stringify(path)});`)
    .join("\n");
  return `${BANNER}
import type { FieldPath, FormAdapter } from "@maroonedog/form-contract";
import { useField } from "@maroonedog/form-contract/react";

${shape.declarations}

declare const adapter: FormAdapter<${shape.rootName}, FieldPath<${shape.rootName}>>;

declare module "@maroonedog/form-contract/react" {
  interface FormTypeRegistry {
    form: typeof adapter;
  }
}

export function everyLeaf(): void {
${calls}
}
`;
}
