// ===========================================================================
// type-program-source.ts — the program the compiler is actually handed.
//
// Every clause of the flagship claim is in here and none of it is stubbed:
// a root type, `FormAdapter<Root, FieldPath<Root>>`, the module augmentation
// that registers it, and real hook calls. The imports resolve to the packages'
// SOURCE, so what is measured is the type the repository maintains rather than
// a `.d.ts` that may have been emitted before the last edit.
//
// WHICH hook is chosen by the path, because the library decides it that way:
// a place goes to `useField` and a rule goes to `useFieldValues`. See
// `hookFor` below.
//
// `declare const adapter` rather than a resolver call, because a resolver
// would drag zod's own inference into the number and the question here is what
// the ADDRESSING costs. The registration is otherwise the one a reader of
// `waypoint-forms.ts` is shown, character for character.
//
// The baseline is this same file with an empty function body. That matters
// more than it looks: `FieldPath<Root>` sits in a type annotation, so the
// compiler resolves it whether or not anybody calls `useField`. Subtracting
// the baseline therefore leaves the cost of ADDRESSING alone, with the union's
// construction already paid — which is the decomposition the report needs and
// the one the disagreeing probes did not make.
// ===========================================================================
import type { ShapeUnderTest } from "./shape-under-test.types.ts";

const BANNER = `// Generated by \`npm run bench:types\`. Rewritten on every program and
// deleted when the run ends. Nothing here is meant to be read by a person.`;

/** A program with no waypoint in it at all — the lib.d.ts floor. */
export const EMPTY_PROGRAM_SOURCE = `${BANNER}\nexport {};\n`;

/**
 * The packages, imported and never used for anything. It separates what the
 * libraries' own source costs from what one application's shape costs, so the
 * shape rows are not reported as if they contained the `./react` entry's own
 * type-checking.
 */
export const PACKAGES_ONLY_PROGRAM_SOURCE = `${BANNER}
import type { FieldPath, FormAdapter } from "@maroonedog/waypoint";
import { useField } from "@maroonedog/waypoint/react";

export type Unused = [FieldPath<{ only: string }>, FormAdapter<unknown>];
export const alsoUnused = useField;
`;

/**
 * Which hook a path is addressed through, decided by the path itself.
 *
 * This is the library's own rule and not the harness's convenience: a place
 * names one value and `useField` takes it, a rule names a column and
 * `useFieldValues` takes it. The generator used to write `useField` for both,
 * which measured a call the compiler now refuses — so the `array-declared`
 * row would have reported the cost of ten type errors rather than the cost of
 * addressing by rule.
 */
const hookFor = (path: string): string =>
  path.includes("[*]") ? "useFieldValues" : "useField";

/**
 * The form's own name, written into every path the way a caller writes one.
 *
 * The key registered below is `form`, and a path names the form it belongs to.
 * An unprefixed call would compile in this program too — one form is
 * registered, so both spellings are legal — but the qualified one is what the
 * README and the site show, so it is the one worth costing. Measuring the
 * spelling nobody is told to write would put a figure on a path the library
 * does not lead with.
 */
const asWritten = (path: string): string => `form:${path}`;

/**
 * The inverse: what the shape catalogue calls the leaf a written path names.
 *
 * The catalogue names its leaves with no form in front of them, and
 * `run-types-bench.ts` compares a refused leaf's path against one of those
 * names as a string. Left qualified, that comparison fails — and it fails in
 * the direction that reads as "nothing was refused", which is what feeds the
 * sentence about how many segments are addressable.
 *
 * Split lexically, on a head standing before the first `.` or `[`, which is
 * the rule the library itself applies on both sides.
 */
export const localPathOf = (spelling: string): string => {
  const colon = spelling.indexOf(":");
  if (colon === -1) return spelling;
  const head = spelling.slice(0, colon);
  return /[.[]/.test(head) ? spelling : spelling.slice(colon + 1);
};

/** The flagship shape, with one call per path given. */
export function typeProgramSource(
  shape: ShapeUnderTest,
  calledPaths: readonly string[]
): string {
  const calls = calledPaths
    .map((path) => `  ${hookFor(path)}(${JSON.stringify(asWritten(path))});`)
    .join("\n");
  return `${BANNER}
import type { FieldPath, FormAdapter } from "@maroonedog/waypoint";
import { useField, useFieldValues } from "@maroonedog/waypoint/react";

${shape.declarations}

declare const adapter: FormAdapter<${shape.rootName}, FieldPath<${shape.rootName}>>;

declare module "@maroonedog/waypoint" {
  interface WaypointForms {
    form: typeof adapter;
  }
}

export function everyLeaf(): void {
${calls}
}
`;
}
