export function median(values) {
  if (values.length === 0 || values.some(value => !Number.isFinite(value))) {
    throw new Error("Measurements must contain finite samples");
  }
  const sorted = [...values].sort((a, b) => a - b);
  const middle = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2;
}

const summary = values => `${median(values).toFixed(2)} [${Math.min(...values).toFixed(2)}–${Math.max(...values).toFixed(2)}]`;
const editedMedian = row => median(row.editedMs.map(sample => sample.ms));

export function editorReport(record) {
  const current = record.samples.filter(row => row.variant === "current");
  const ids = [...new Set(current.map(row => row.workload.id))];
  const shapeRows = ids.map(id => {
    const row = current.find(row => row.workload.id === id);
    return `| ${id} | ${row.workload.forms} | ${row.workload.depth} | ${row.leavesPerForm} | ${row.backgroundCalls} | ${row.applicationFiles} |`;
  });
  const timingRows = [];
  const diagnosticRows = [];
  const comparisonRows = [];
  const memoryRows = [];
  for (const id of ids) {
    for (const operation of ["completion", "hover", "diagnostics"]) {
      const rows = current.filter(row => row.workload.id === id && row.operation === operation);
      timingRows.push(`| ${id} | ${operation} | ${summary(rows.map(row => row.coldMs))} | ${summary(rows.map(row => median(row.warmMs)))} | ${summary(rows.map(editedMedian))} |`);
      if (operation === "diagnostics") {
        diagnosticRows.push(`| ${id} | ${summary(rows.map(row => median(row.editedMs.filter(sample => sample.invalid).map(sample => sample.ms))))} | ${summary(rows.map(row => median(row.editedMs.filter(sample => !sample.invalid).map(sample => sample.ms))))} |`);
      }
      const ratios = rows.map(row => {
        const baseline = record.samples.find(other => other.workload.id === id && other.operation === operation && other.trial === row.trial && other.variant === "without-identity");
        return {
          cold: (row.coldMs / baseline.coldMs - 1) * 100,
          edited: (editedMedian(row) / editedMedian(baseline) - 1) * 100,
        };
      });
      comparisonRows.push(`| ${id} | ${operation} | ${summary(ratios.map(ratio => ratio.cold))}% | ${summary(ratios.map(ratio => ratio.edited))}% |`);
      memoryRows.push(`| ${id} | ${operation} | ${summary(rows.map(row => row.heapUsedBytes / 1024 ** 2))} | ${summary(rows.map(row => row.rssBytes / 1024 ** 2))} |`);
    }
  }
  return `# Editor service measurements — emitted declarations

Generated by \`npm run bench:editor\`. Raw samples: [measurements-editor.json](measurements-editor.json).
Timings are observations, not CI thresholds or a claim about every editor.

## Workloads

| workload | forms | path segments | leaves/form | background hook calls | application files |
|---|---:|---:|---:|---:|---:|
${shapeRows.join("\n")}

Every leaf is a string in a distinct nested object type, branching factor three.
Every leaf has a background hook call, split across view files; each form has a
separate registration file. A probe file adds one more call. The first two rows
hold shape and call count constant while changing file count. The other rows
change total shape/call size too; they do not isolate registry size by itself.
No schema resolver runs, so these numbers exclude vendor inference costs.

## Request latency (milliseconds)

Each cell is median [minimum–maximum] across ${record.trials} independent Node
processes. Warm/edited cells first take a median within each process. Cold is the
first request to a fresh TypeScript Language Service with no program preloaded;
it includes program construction and dependency reads, but excludes Node startup,
TypeScript import, fixture generation and Language Service construction. OS caches
are not cleared. Every operation and variant gets a separate process.

Warm means the same request with unchanged input (${record.warmRepeats} repetitions).
Edited means a request after changing the path literal in the probe (${record.editRepeats}
edits). Completion/hover alternate two valid paths; diagnostics alternate a typo
and its correction. Updates use full script snapshots without a text change range.
Only the probe file's diagnostics are timed, not project-wide background checking.

| workload | operation | cold | warm unchanged | after edit |
|---|---|---:|---:|---:|
${timingRows.join("\n")}

The diagnostics edit aggregate combines invalid and recovered states; separately:

| workload | typo introduced (ms) | typo corrected (ms) |
|---|---:|---:|
${diagnosticRows.join("\n")}

## Cost of retaining adapter type identity

This is a controlled counterfactual, **not an alternative safe configuration**.
The host removes only the optional identity member from the emitted FormAdapter
declaration in memory. The repository and package are never edited. That restores
the structural-erasure hazard, so a faster counterfactual does not justify shipping it.
Other fixes and all other declarations remain identical; this is not a historical
commit benchmark. Variant order alternates by trial/workload/operation and workload
order rotates by trial. Runs are sequential to avoid competing benchmark workers.

Cells give median [minimum–maximum] of paired percentage changes, current versus
counterfactual. Positive means current is slower. Small or inconsistent changes
within the observed spread should not be interpreted as a regression or a gain.

| workload | operation | cold change | after-edit change |
|---|---|---:|---:|
${comparisonRows.join("\n")}

## Memory at the end of measured requests (MiB)

Process heap/RSS samples include the harness, compiler, declarations, snapshots and
application. They are neither peaks nor retained memory after GC. They are captured
before the untimed project-wide correctness audit; garbage collection is not forced.

| workload | operation | heap used | RSS |
|---|---|---:|---:|
${memoryRows.join("\n")}

## Validity and boundaries

Every timed completion must contain the expected paths; every hover must preserve
\`string | undefined\`; every invalid diagnostic must be TS2345 and correcting it
must clear it. After timing, every generated application file is checked and a
deliberate typo is rejected. Missing responses and failed workers abort the report.
The host asserts that waypoint resolves through package exports to \`dist/*.d.ts\`
and that no waypoint source implementation was loaded. This is the workspace's
emitted package, not a separately installed tarball. \`skipLibCheck\` is enabled;
dependency-declaration conflicts are tested separately by the composition suite.

This calls TypeScript's public Language Service API. It does not measure an editor
extension, tsserver IPC/debouncing, rendering suggestions, completion details, a
keystroke-to-pixel delay, project-reference scheduling, schema edits, or runtime
input/row performance. Synthetic all-string forms do not establish a universal
supported form count. Warm no-edit results primarily measure cached work.

## Provenance

- Recorded: ${record.recordedAt}
- TypeScript: ${record.typescript}; Node: ${record.node}
- Machine: ${record.machine.cpu}; ${record.machine.cores} logical CPUs; ${record.machine.memoryGiB} GiB; ${record.machine.platform}
- Package version: ${record.packageVersion}
- Git HEAD: ${record.revision} (working-tree declarations; uncommitted changes may be included)
- Emitted declaration SHA-256: \`${record.declarationHash}\`
- Harness SHA-256: \`${record.harnessHash}\`
- Compiler options: ES2020, NodeNext resolution/module, strict, exactOptionalPropertyTypes,
  noUncheckedIndexedAccess, skipLibCheck, types=[], noEmit. Default libraries include DOM.
- Processes: ${record.samples.length}; elapsed: ${(record.elapsedMs / 1000).toFixed(1)} seconds

Re-run on the same machine and compiler before comparing a future revision. The
declaration hash identifies the actual measured state more precisely than HEAD.
`;
}
